#ifndef __RETRO_STRING__
#define __RETRO_STRING__

#define NUM_STRING	151

extern const char* pSelLangStr[NUM_STRING];

void set_multi_language_strings();

#define RETRO_DEPTH32_CAT_DESC				pSelLangStr[  0]
#define RETRO_DEPTH32_CAT_INFO				pSelLangStr[  1]
#define RETRO_VERTICAL_CAT_DESC				pSelLangStr[  2]
#define RETRO_VERTICAL_CAT_INFO				pSelLangStr[  3]
#define RETRO_VERTICAL_VALUE_2				pSelLangStr[  4]
#define RETRO_VERTICAL_VALUE_4				pSelLangStr[  5]
#define RETRO_FORCE60_CAT_DESC				pSelLangStr[  6]
#define RETRO_FORCE60_CAT_INFO				pSelLangStr[  7]
#define RETRO_PATCHED_CAT_DESC				pSelLangStr[ 36]
#define RETRO_PATCHED_CAT_INFO				pSelLangStr[ 37]
#define RETRO_ANALOG_CAT_DESC				pSelLangStr[ 48]
#define RETRO_ANALOG_CAT_INFO				pSelLangStr[ 49]
#define RETRO_CROSSHAIR_CAT_DESC			pSelLangStr[ 50]
#define RETRO_CROSSHAIR_CAT_INFO			pSelLangStr[ 51]
#define RETRO_CROSSHAIR_VALUE_0				pSelLangStr[ 52]
#define RETRO_CROSSHAIR_VALUE_1				pSelLangStr[ 53]
#define RETRO_CROSSHAIR_VALUE_2				pSelLangStr[ 54]
#define RETRO_CPUSPEED_CAT_DESC				pSelLangStr[ 23]
#define RETRO_CPUSPEED_CAT_INFO				pSelLangStr[ 24]
#define RETRO_CYCLONE_CAT_DESC				pSelLangStr[ 55]
#define RETRO_CYCLONE_CAT_INFO				pSelLangStr[ 56]
#define RETRO_HISCORES_CAT_DESC				pSelLangStr[ 34]
#define RETRO_HISCORES_CAT_INFO				pSelLangStr[ 35]
#define RETRO_DIAGNOSTIC_CAT_DESC			pSelLangStr[ 25]
#define RETRO_DIAGNOSTIC_CAT_INFO			pSelLangStr[ 26]
#define RETRO_DIAGNOSTIC_VALUE_0			pSelLangStr[ 27]
#define RETRO_DIAGNOSTIC_VALUE_1			pSelLangStr[ 28]
#define RETRO_DIAGNOSTIC_VALUE_3			pSelLangStr[ 29]
#define RETRO_DIAGNOSTIC_VALUE_5			pSelLangStr[ 30]
#define RETRO_DIAGNOSTIC_VALUE_6			pSelLangStr[ 31]
#define RETRO_DIAGNOSTIC_VALUE_8			pSelLangStr[ 32]
#define RETRO_DIAGNOSTIC_VALUE_10			pSelLangStr[ 33]
#define RETRO_NEOGEO_CAT_DESC				pSelLangStr[113]
#define RETRO_NEOGEO_CAT_INFO				pSelLangStr[114]
#define RETRO_NGMODE_DEF_DESC				pSelLangStr[ 57]
#define RETRO_NGMODE_DEF_INFO				pSelLangStr[ 58]
#define RETRO_NGMODE_LABEL_0				pSelLangStr[ 60]
#define RETRO_MEMCARD_DEF_DESC				pSelLangStr[ 61]
#define RETRO_MEMCARD_DEF_INFO				pSelLangStr[ 62]
#define RETRO_MEMCARD_VALUE_1				pSelLangStr[ 63]
#define RETRO_MEMCARD_VALUE_2				pSelLangStr[ 64]
#define RETRO_DEBUG11_DEF_DESC				pSelLangStr[ 65]
#define RETRO_DEBUG11_DEF_INFO				pSelLangStr[ 66]
#define RETRO_DEBUG12_DEF_DESC				pSelLangStr[ 67]
#define RETRO_DEBUG12_DEF_INFO				pSelLangStr[ 68]
#define RETRO_DEBUG13_DEF_DESC				pSelLangStr[ 69]
#define RETRO_DEBUG13_DEF_INFO				pSelLangStr[ 70]
#define RETRO_DEBUG14_DEF_DESC				pSelLangStr[ 71]
#define RETRO_DEBUG14_DEF_INFO				pSelLangStr[ 72]
#define RETRO_DEBUG15_DEF_DESC				pSelLangStr[ 73]
#define RETRO_DEBUG15_DEF_INFO				pSelLangStr[ 74]
#define RETRO_DEBUG16_DEF_DESC				pSelLangStr[ 75]
#define RETRO_DEBUG16_DEF_INFO				pSelLangStr[ 76]
#define RETRO_DEBUG17_DEF_DESC				pSelLangStr[ 77]
#define RETRO_DEBUG17_DEF_INFO				pSelLangStr[ 78]
#define RETRO_DEBUG18_DEF_DESC				pSelLangStr[ 79]
#define RETRO_DEBUG18_DEF_INFO				pSelLangStr[ 80]
#define RETRO_DEBUG21_DEF_DESC				pSelLangStr[ 81]
#define RETRO_DEBUG21_DEF_INFO				pSelLangStr[ 82]
#define RETRO_DEBUG22_DEF_DESC				pSelLangStr[ 83]
#define RETRO_DEBUG22_DEF_INFO				pSelLangStr[ 84]
#define RETRO_DEBUG23_DEF_DESC				pSelLangStr[ 85]
#define RETRO_DEBUG23_DEF_INFO				pSelLangStr[ 86]
#define RETRO_DEBUG24_DEF_DESC				pSelLangStr[ 87]
#define RETRO_DEBUG24_DEF_INFO				pSelLangStr[ 88]
#define RETRO_DEBUG25_DEF_DESC				pSelLangStr[ 89]
#define RETRO_DEBUG25_DEF_INFO				pSelLangStr[ 90]
#define RETRO_DEBUG26_DEF_DESC				pSelLangStr[ 91]
#define RETRO_DEBUG26_DEF_INFO				pSelLangStr[ 92]
#define RETRO_DEBUG27_DEF_DESC				pSelLangStr[ 93]
#define RETRO_DEBUG27_DEF_INFO				pSelLangStr[ 94]
#define RETRO_DEBUG28_DEF_DESC				pSelLangStr[ 95]
#define RETRO_DEBUG28_DEF_INFO				pSelLangStr[ 96]
#define RETRO_FRAME_CAT_DESC				pSelLangStr[115]
#define RETRO_FRAME_CAT_INFO				pSelLangStr[116]
#define RETRO_FRAMESKIP_DEF_DESC			pSelLangStr[ 16]
#define RETRO_FRAMESKIP_DEF_INFO			pSelLangStr[ 17]
#define RETRO_FRAMESKIP_VALUE_1				pSelLangStr[ 18]
#define RETRO_FRAMESKIP_VALUE_2				pSelLangStr[ 19]
#define RETRO_FRAMESKIP_VALUE_3				pSelLangStr[ 20]
#define RETRO_FSTHRESHOLD_DEF_DESC			pSelLangStr[ 21]
#define RETRO_FSTHRESHOLD_DEF_INFO			pSelLangStr[ 22]
#define RETRO_FSFIXED_DEF_DESC				pSelLangStr[  8]
#define RETRO_FSFIXED_DEF_INFO				pSelLangStr[  9]
#define RETRO_FSFIXED_LABEL_0				pSelLangStr[ 10]
#define RETRO_FSFIXED_LABEL_1				pSelLangStr[ 11]
#define RETRO_FSFIXED_LABEL_2				pSelLangStr[ 12]
#define RETRO_FSFIXED_LABEL_3				pSelLangStr[ 13]
#define RETRO_FSFIXED_LABEL_4				pSelLangStr[ 14]
#define RETRO_FSFIXED_LABEL_5				pSelLangStr[ 15]
#define RETRO_AUDIO_CAT_DESC				pSelLangStr[117]
#define RETRO_AUDIO_CAT_INFO				pSelLangStr[118]
#define RETRO_SAMPLERATE_DEF_DESC			pSelLangStr[ 38]
#define RETRO_SAMPLERATE_DEF_INFO			pSelLangStr[ 39]
#define RETRO_SAMPLE_INTERPOLATION_DEF_DESC	pSelLangStr[ 40]
#define RETRO_SAMPLE_INTERPOLATION_DEF_INFO	pSelLangStr[ 41]
#define RETRO_SAMPLE_INTERPOLATION_VALUE_1	pSelLangStr[ 42]
#define RETRO_SAMPLE_INTERPOLATION_VALUE_2	pSelLangStr[ 43]
#define RETRO_FM_INTERPOLATION_DEF_DESC		pSelLangStr[ 44]
#define RETRO_FM_INTERPOLATION_DEF_INFO		pSelLangStr[ 45]
#define RETRO_FM_INTERPOLATION_VALUE_1		RETRO_SAMPLE_INTERPOLATION_VALUE_2
#define RETRO_LOWPASS_FILTER_DEF_DESC		pSelLangStr[ 46]
#define RETRO_LOWPASS_FILTER_DEF_INFO		pSelLangStr[ 47]
#define RETRO_DIP_CAT_DESC					pSelLangStr[119]
#define RETRO_DIP_CAT_INFO					pSelLangStr[120]
#define RETRO_NGBIOS_DEF_INFO_0				pSelLangStr[110]
#define RETRO_NGBIOS_DEF_INFO_1				pSelLangStr[111]
#define RETRO_CHEAT_CAT_DESC				pSelLangStr[121]
#define RETRO_CHEAT_CAT_INFO				pSelLangStr[122]
#define RETRO_CHEAT_DEF_INFO				pSelLangStr[112]
#define RETRO_IPS_CAT_DESC					pSelLangStr[124]
#define RETRO_IPS_CAT_INFO					pSelLangStr[123]
#define RETRO_IPS_DEF_INFO					pSelLangStr[125]
#define RETRO_ROMDATA_CAT_INFO				pSelLangStr[127]
#define RETRO_ROMDATA_DEF_INFO				pSelLangStr[126]
#define RETRO_DEBUG_CAT_DESC				pSelLangStr[128]
#define RETRO_DEBUG_CAT_INFO				pSelLangStr[129]
#define RETRO_DEBUG_DEF_INFO				pSelLangStr[ 97]
#define RETRO_DEBUG_LAYER_1_DEF_DESC		pSelLangStr[ 98]
#define RETRO_DEBUG_LAYER_2_DEF_DESC		pSelLangStr[ 99]
#define RETRO_DEBUG_LAYER_3_DEF_DESC		pSelLangStr[100]
#define RETRO_DEBUG_LAYER_4_DEF_DESC		pSelLangStr[101]
#define RETRO_DEBUG_SPRITE_1_DEF_DESC		pSelLangStr[102]
#define RETRO_DEBUG_SPRITE_2_DEF_DESC		pSelLangStr[103]
#define RETRO_DEBUG_SPRITE_3_DEF_DESC		pSelLangStr[104]
#define RETRO_DEBUG_SPRITE_4_DEF_DESC		pSelLangStr[105]
#define RETRO_DEBUG_SPRITE_5_DEF_DESC		pSelLangStr[106]
#define RETRO_DEBUG_SPRITE_6_DEF_DESC		pSelLangStr[107]
#define RETRO_DEBUG_SPRITE_7_DEF_DESC		pSelLangStr[108]
#define RETRO_DEBUG_SPRITE_8_DEF_DESC		pSelLangStr[109]
#define RETRO_SOCD_DESC						pSelLangStr[141]
#define RETRO_SOCD_INFO						pSelLangStr[142]
#define RETRO_SOCD_LABEL_1					pSelLangStr[143]
#define RETRO_SOCD_LABEL_2					pSelLangStr[144]
#define RETRO_SOCD_LABEL_3					pSelLangStr[145]
#define RETRO_SOCD_LABEL_4					pSelLangStr[146]
#define RETRO_SOCD_LABEL_5					pSelLangStr[147]
#define RETRO_SOCD_LABEL_6					pSelLangStr[148]
#define RETRO_RESOLUTION_DESC				pSelLangStr[149]
#define RETRO_RESOLUTION_INFO				pSelLangStr[150]

/* UGUI */
#define RETRO_ERROR_MESSAGES_00				pSelLangStr[ 59]
#define RETRO_ERROR_MESSAGES_01				pSelLangStr[130]
#define RETRO_ERROR_MESSAGES_02				pSelLangStr[131]
#define RETRO_ERROR_MESSAGES_03				pSelLangStr[132]
#define RETRO_ERROR_MESSAGES_04				pSelLangStr[133]
#define RETRO_ERROR_MESSAGES_05				pSelLangStr[134]
#define RETRO_ERROR_MESSAGES_06				pSelLangStr[135]
#define RETRO_ERROR_MESSAGES_07				pSelLangStr[136]
#define RETRO_ERROR_MESSAGES_08				pSelLangStr[137]
#define RETRO_ERROR_MESSAGES_09				pSelLangStr[138]
#define RETRO_ERROR_MESSAGES_10				pSelLangStr[139]
#define RETRO_ERROR_MESSAGES_11				pSelLangStr[140]


#endif
