#!/usr/bin/env python3
#
# spv2h.py -- convert a SPIR-V binary blob to a C header that
# embeds it as a static const uint32_t array.  Used by
# tools/shaders_regen.sh to materialize the shader bytecode
# headers under common/shaders/generated/spv/.
#
# This script is OFFLINE tooling -- it never runs as part of
# building the tyrquake core itself.  The produced .h files
# are committed to the repository; the build sees only the
# generated bytecode arrays, not the .glsl source or this
# script.
#
# Usage:
#   spv2h.py <input.spv> <output.h> <symbol_name>
#
# Example:
#   spv2h.py /tmp/vs.spv \
#       common/shaders/generated/spv/fullscreen_quad_vs.h \
#       spv_fullscreen_quad_vs
#
# Produces:
#   /* Auto-generated from common/shaders/src/fullscreen_quad.vert.
#    * Do not edit; run tools/shaders_regen.sh to regenerate. */
#   static const uint32_t spv_fullscreen_quad_vs[] = {
#       0x07230203, ... (N words)
#   };
#   static const size_t spv_fullscreen_quad_vs_size = sizeof(spv_fullscreen_quad_vs);

import os
import struct
import sys


WORDS_PER_LINE = 8


def main(argv):
    if len(argv) != 4:
        sys.stderr.write(
            "usage: spv2h.py <input.spv> <output.h> <symbol_name>\n")
        sys.exit(2)

    in_path, out_path, sym = argv[1], argv[2], argv[3]

    with open(in_path, "rb") as f:
        data = f.read()

    if len(data) % 4:
        sys.stderr.write(
            "spv2h.py: %s is not a multiple of 4 bytes (got %d)\n"
            % (in_path, len(data)))
        sys.exit(1)

    words = struct.unpack("<%dI" % (len(data) // 4), data)
    if not words or words[0] != 0x07230203:
        sys.stderr.write(
            "spv2h.py: %s does not start with the SPIR-V magic number "
            "0x07230203 (got 0x%08x)\n"
            % (in_path, words[0] if words else 0))
        sys.exit(1)

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)

    src_name = os.path.basename(in_path).replace(".spv", "")

    lines = []
    lines.append("/*")
    lines.append(" * Auto-generated SPIR-V bytecode for the tyrquake Vulkan")
    lines.append(" * backend.  Do not edit by hand -- run")
    lines.append(" * tools/shaders_regen.sh to regenerate from the GLSL")
    lines.append(" * source under common/shaders/src/.")
    lines.append(" *")
    lines.append(" * Symbol: %s" % sym)
    lines.append(" * Word count: %d (%d bytes)" % (len(words), len(data)))
    lines.append(" */")
    lines.append("")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("static const uint32_t %s[] = {" % sym)
    for i in range(0, len(words), WORDS_PER_LINE):
        chunk = words[i:i + WORDS_PER_LINE]
        line = "    " + " ".join("0x%08x," % w for w in chunk)
        lines.append(line)
    lines.append("};")
    lines.append("")
    lines.append("static const size_t %s_size = sizeof(%s);" % (sym, sym))
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main(sys.argv)
