/*
Copyright (C) 1996-1997 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

#ifndef PROGS_H
#define PROGS_H

#include "pr_comp.h"		/* defs shared with qcc */
#include "progdefs.h"		/* generated by program cdefs */
#include "common.h"

#include <streams/file_stream.h>

typedef union eval_s {
    string_t string;
    float _float;
    float vector[3];
    func_t function;
    int _int;
    int edict;
} eval_t;

#define	MAX_ENT_LEAFS	48
typedef struct edict_s {
    qboolean free;
    link_t area;		/* linked to a division node or leaf */

    int num_leafs;
    int leafnums[MAX_ENT_LEAFS];

    entity_state_t baseline;

    float freetime;		/* sv.time when the object was freed */
    entvars_t v;		/* C exported fields from progs */
/* other fields from progs come immediately after */
} edict_t;

#define	EDICT_FROM_AREA(l) container_of(l,edict_t,area)

/* ============================================================================ */

extern dprograms_t *progs;
extern dfunction_t *pr_functions;
extern char *pr_strings;
extern int pr_strings_size;
extern dstatement_t *pr_statements;
extern globalvars_t *pr_global_struct;
extern float *pr_globals;	/* same as pr_global_struct */

extern int pr_edict_size;	/* in bytes */

/* ============================================================================ */

void PR_Init(void);

void PR_ExecuteProgram(func_t fnum);
void PR_LoadProgs(void);

void PR_Profile_f(void);

edict_t *ED_Alloc(void);
void ED_Free(edict_t *ed);

/* returns a copy of the string allocated from the server's string heap */

void ED_Print(edict_t *ed);
void ED_Write(RFILE *f, edict_t *ed);
const char *ED_ParseEdict(const char *data, edict_t *ent);

void ED_WriteGlobals(RFILE *f);
void ED_ParseGlobals(const char *data);

void ED_LoadFromFile(const char *data);

/* define EDICT_NUM(n) ((edict_t *)(sv.edicts+ (n)*pr_edict_size)) */
/* define NUM_FOR_EDICT(e) (((byte *)(e) - sv.edicts)/pr_edict_size) */

edict_t *EDICT_NUM(int n);
int NUM_FOR_EDICT(const edict_t *e);

/* PROG_TO_EDICT converts a QuakeC-stored byte offset into an
 * edict_t pointer.  The offset is set either by the engine
 * (always valid) or by bytecode (self/other/world globals,
 * eval_t.edict fields).  Bytecode-set values aren't bounded
 * by the bytecode store ops -- those validate the offset
 * within pr_globals[] but not the *contents* of an edict
 * field -- so a hostile progs.dat can plant a value that
 * makes the resulting pointer land outside sv.edicts.
 *
 * Convert to an inline function so we can bound the offset
 * at every consumer.  The bound matches NUM_FOR_EDICT's
 * pointer-extent check: offset must be a non-negative
 * multiple of pr_edict_size, less than max_edicts *
 * pr_edict_size. */
edict_t *PROG_TO_EDICT(int e);

#define	NEXT_EDICT(e) ((edict_t *)( (byte *)e + pr_edict_size))

#define	EDICT_TO_PROG(e) ((byte *)e - (byte *)sv.edicts)

/* ============================================================================ */

#define	G_FLOAT(o) (pr_globals[o])
#define	G_INT(o) (*(int *)&pr_globals[o])
#define	G_EDICT(o) PROG_TO_EDICT(*(int *)&pr_globals[o])
#define G_EDICTNUM(o) NUM_FOR_EDICT(G_EDICT(o))
#define	G_VECTOR(o) (&pr_globals[o])
#define	G_STRING(o) (PR_GetString(*(string_t *)&pr_globals[o]))
#define	G_FUNCTION(o) (*(func_t *)&pr_globals[o])

#define	E_FLOAT(e,o) (((float*)&e->v)[o])
#define	E_INT(e,o) (*(int *)&((float*)&e->v)[o])
#define	E_VECTOR(e,o) (&((float*)&e->v)[o])
#define	E_STRING(e,o) (PR_GetString(*(string_t *)&((float*)&e->v)[o]))

typedef void (*builtin_t) (void);
extern builtin_t *pr_builtins;
extern int pr_numbuiltins;

extern int pr_argc;

extern dfunction_t *pr_xfunction;
extern int pr_xstatement;

extern unsigned short pr_crc;

void PR_RunError(const char *error, ...);

char *PR_GlobalString(int ofs);
char *PR_GlobalStringNoContents(int ofs);

void ED_PrintNum(int ent);

eval_t *GetEdictFieldValue(edict_t *ed, const char *field);

/*
 * PR Strings stuff
 */
void PR_InitStringTable(void);
const char *PR_GetString(int num);
int PR_SetString(const char *s);

/*
 * Somehow, I don't think this should be exposed - but better to have it here
 * than have hidden exports between .c files.
 */
void PF_changeyaw(void);

#endif /* PROGS_H */
