name: Test Stable-Retro

on: [pull_request, push]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest  # todo, add more OS systems to see if they work as well
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']  # '3.11'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install git cmake capnproto zlib1g-dev g++ build-essential python3-dev python3-pip pkg-config libzip-dev software-properties-common libbz2-dev xvfb python3-opengl

      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip cmake wheel setuptools pytest
          pip install -e .

      - name: Run tests
        run: xvfb-run -s '-screen 0 1024x768x24' pytest
