name: Test C++ Stable-Retro code

on: [pull_request, push]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest  # todo, add more OS systems to see if they work as well

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake capnproto zlib1g-dev build-essential pkg-config libzip-dev software-properties-common libbz2-dev python3-opengl

      - name: Build and run tests
        run: scripts/test-cpp.sh
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: 2
